export const CharacterList = [
  { name: 'None' },
  { name: 'Zetterburn' },
  { name: 'Orcane' },
  { name: 'Wrastor' },
  { name: 'Kragg' },
  { name: 'Forsburn' },
  { name: 'Maypul' },
  { name: 'Absa' },
  { name: 'Etalus' },
  { name: 'Ranno' },
  { name: 'Clairen' },
  { name: 'Sylvanos' },
  { name: 'Elliana' },
  { name: 'Ori and Sein' },
  { name: 'Shovel Knight' },
  { name: 'Mollo' },
  { name: 'Hodan' },
  { name: 'Pomme' },
  { name: 'Olympia' },
];
